### ISSUE TITLE
Barcharts: selektierte Kanäle

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#10]
Die Anzeige selektierter Barchart-Kanäle per dickerer Umrandung ist problematisch, insbesondere wenn mehrere Kanäle aktiv sind (Balken schieben sich ineinander, in die nächste Gruppe etc.).
Lösungsvorschlag: Visualisierung nicht durch Umrandung, sondern durch Reduzierung der Deckkraft der nicht selektierten Kanäle - das verändert nicht die Geometrie der Balken und würde auch für gleichzeitige Selektion mehrerer Kanäle funktionieren.

**Comment by andig** [comment]
> Lösungsvorschlag 

das ist doof weil ich dann den Kanal ja nicht mehr so definieren kann wie ich egtl. möchte. Spontan würde ich die Umrandung höchstens wieder ausbauen.

**Comment by frankrichter** [comment]
Am 26.01.2017 19:54 schrieb "andig" <notifications@github.com>:
>>
>> Lösungsvorschlag
>
> das ist doof weil ich dann den Kanal ja nicht mehr so definieren kann wie
ich egtl. möchte.

Wie meinst du das?

> Spontan würde ich die Umrandung höchstens wieder ausbauen.

Lässt sich die Umrandung so machen  dass sie die Geometrie des Balkens
nicht ändert (von der Kontur aus nach innen)?

**Comment by andig** [comment]
Hast Du mal einen Screenshot? Passiert bei mir auch, würde mich aber nixht stören?

**Comment by frankrichter** [comment]
Die Umrandung mag noch ok sein, aber dass sich die Balken bei Selektion verschieben (u.U. bis in die nächste Gruppe) ist sehr verwirrend. Weiterhin müsste gewährleistet sein, dass der selektierte Balken nicht von anderen verdeckt wird (gibts da sowas wie z-index?).

![screenshot 2017-02-05 22 13 58](https://cloud.githubusercontent.com/assets/13228024/22629934/c5907934-ebf0-11e6-83ae-cb442e8dca3f.png)
![screenshot 2017-02-05 22 14 15](https://cloud.githubusercontent.com/assets/13228024/22629943/deec29d2-ebf0-11e6-82cb-3f554870098d.png)
![screenshot 2017-02-05 22 14 30](https://cloud.githubusercontent.com/assets/13228024/22629945/e3645eb2-ebf0-11e6-9369-5131b55e557e.png)
![screenshot 2017-02-05 22 14 44](https://cloud.githubusercontent.com/assets/13228024/22629949/eaafc346-ebf0-11e6-8025-2fb511a77e50.png)

**Comment by andig** [comment]
Richtig sexy is das nicht, aber so richtig schrecklich find ichs auch nicht. Fürs Erste könnte ich einfach anbieten dass bei Selektion gar nix passiert?

**Comment by frankrichter** [comment]
problematisch für die Übersicht finde ich, dass sich die selektierten Kanäle je nach Ursprungsposition bis zur nächsten Gruppe, also zum falschen Timestamp verschieben. Wenn sich das nicht einfach beheben lässt, wäre ich tatsächlich für erstmal deaktivieren.

**Comment by andig** [comment]
Schau mal bitte plot.js#328:

````
		else if (style == 'bars') {
			$.extend(serie, {
				bars: {
					show:       true,
					lineWidth:  0,
					fill: 			entity.selected ? 1.0 : 0.8,
					order:      index++ // only used for bars
				}
			});
		}

**Comment by frankrichter** [comment]
Gefällt mir super!

**Comment by andig** [comment]
Bitte testen

**Comment by frankrichter** [comment]
check
