### ISSUE TITLE
nach Login keine Kanäle

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#11]
Nach erfolgreichem Login werden keine abonnierten Kanäle nachgeladen, erst ein Refresh füllt Kanalliste und Chart.
Ich bilde mir ein, dass das schon mal funktioniert hat - kann es mit dem merge von gestern zu tun haben?

**Comment by andig** [comment]
Was heisst das- hast Du GET Requests erlaubt?

**Comment by frankrichter** [comment]
Hab bei GET statt allow auch auth konfiguriert.
Am 20.01.2017 19:03 schrieb "andig" <notifications@github.com>:

**Comment by frankrichter** [comment]
Hab jetzt das `git pull` von gestern rückgängig gemacht, konnte aber keine Änderung feststellen. Vielleicht träume ich das auch, dass sich die abonnierten Kanäle nach erfolgreichem Login automatisch geladen haben...

**Comment by andig** [comment]
Das lässt sich fixen, mach ruhig Issues auf, ich räume die nach und nach weg.

**Comment by andig** [comment]
Geht bei mir- wie sieht Deine vz.conf bzgl. firewall aus? Kann ich das bei Dir nachtesten? Branch next, aktueller Stand?

**Comment by frankrichter** [comment]
Am 26.01.2017 19:20 schrieb "andig" <notifications@github.com>:
>
> Geht bei mir- wie sieht Deine vz.conf bzgl. firewall aus?

Bei GET ebenfalls auth, sonst Lieferzustand.

> Kann ich das bei Dir nachtesten?

Zugangsdaten müsstest du haben (SMS). Fühl dich wie zu Hause...

> Branch next, aktueller Stand?

Check

**Comment by andig** [comment]
Kann ich nicht nachvollziehen:

1. Erstes Login
2. Bezug abonnieren
3. Token cookie löschen
4. Reload
5. Erneutes login

--> Seite mit Bezug geladen

**Comment by frankrichter** [comment]
Seltsam, ich hab hier definitiv mit 3 Browsern (IE11/Chrome Win/Chrome
Android) nach neuem Login zunächst keine Kanäle.

Ich mach jetzt mal ein git pull, um die Sache mit dem Authtoken zu fixen,
vielleicht ändert das was.

Am 26. Januar 2017 um 21:15 schrieb andig <notifications@github.com>:

**Comment by frankrichter** [comment]
Ne, das ist anders: wenn ich genau das gleiche mache wie du geht's bei mir
auch. Es scheitert dann, wenn mehr als 1 Kanal abonniert ist.

Am 26. Januar 2017 um 21:15 schrieb andig <notifications@github.com>:

**Comment by andig** [comment]
> Es scheitert dann, wenn mehr als 1 Kanal abonniert ist.

Mir schwant Schlimmes... da droht Serialisierung der MW Calls wenn der Token fehlt. Das wird wieder frickelig.

**Comment by frankrichter** [comment]
Lass dir Zeit, jetzt wo das Token die vorgesehene Gültigkeit hat kommt es
ja nicht mehr so oft vor.

>

**Comment by andig** [comment]
Grad bei Dir nachgetestet- geht auch wenn ich 2 Kanäle abonniere, gleiches Spiel wie oben. Kannst Du mal schauen welche Cookies existieren wenn Du zur Anmeldung aufgefordert wirst?

Steps to repro für die Fehler?

**Comment by frankrichter** [comment]
Strange...

meine Schritte:
1) Login in neuer Chrome Ikognito-Session (also sauber)
2) Bezug und Lieferung abonniert
3) Cookie vz_authtoken gelöscht (ansonsten existiert nur vz_entities)
4) Reload
5) neuer Login, danach keine Kanäle vorhanden

und eben erstmals gesehen: Konsole hat 2 401-Fehler für die beiden
GET-Requests


Am 27. Januar 2017 um 16:34 schrieb andig <notifications@github.com>:

**Comment by andig** [comment]
Exakt so getestet- geht bei mir auf Deiner Installation???

**Comment by frankrichter** [comment]
Dann muss es wohl eine Browser-Sache sein, so wie gestern mit dem Cookie.
Die zwei fehlgeschlagenen GETs kommen übrigens sofort beim Reload nach
Löschung des Tokens, darf das so sein?

2017-01-27 16:55 GMT+01:00 andig <notifications@github.com>:

**Comment by frankrichter** [comment]
Ok, den 401er gibt es bei mir auch mit einem abonnierten Kanal, aber da
erfolgt offenbar nach dem Login ein neuer Versuch.

Am 27. Januar 2017 um 17:02 schrieb Frank Richter <frank.richter83@gmail.com

**Comment by andig** [comment]
> Die zwei fehlgeschlagenen GETs kommen übrigens sofort beim Reload nach Löschung des Tokens, darf das so sein?

Evtl. ein Timingissue weil Du lokal drauf gehst? Kannst Du bei Chrome mal versuchen Netzwerkverzögerung zu emulieren?

**Comment by frankrichter** [comment]
Ist bei mir auch nicht lokal, bin 150km weg von der Kiste.
Am 27.01.2017 17:21 schrieb "andig" <notifications@github.com>:

**Comment by frankrichter** [comment]
Eben mal per IE11 geöffnet: Mein Login hatte er vergessen, aber sofort nach
Login wurden 3 Kanäle geladen. Leider kann ich es derzeit nicht
reproduzieren, weil ich keine Ahnung habe wie ich hier selektiv das Token
löschen kann. Ich finde nicht mal die Cookies zur VZ-URL...
Aber wohl tatsächlich eine browserspezifische Sache.

Am 27. Januar 2017 um 17:23 schrieb Frank Richter <frank.richter83@gmail.com

**Comment by frankrichter** [comment]
Mit Firefox klappt es auch.

Am 27. Januar 2017 um 17:33 schrieb Frank Richter <frank.richter83@gmail.com

**Comment by andig** [comment]
Bei mir gehts mit Chrome auf OSX, mehr hab ich noch nicht getestet.

**Comment by frankrichter** [comment]
Edge (Windows 10) kann es ebenfalls.

**Comment by andig** [comment]
Es nutzt nix- den würde ich schließen bis es einen nachvollziehbaren Fall gibt an den ich ran kann. Wie gesagt geht bei mir auch Chrome gegen Deine Installation :(

**Comment by frankrichter** [comment]
Ist wohl eine Eigenheit von Chrome auf Windows. Wenn eine Windows-Kiste zum Testen fehlt, kann ich TeamViewer-Zugang anbieten.

**Comment by andig** [comment]
ok, meld mich wenn ich Zeit dafür habe- evtl. geht Mi abend was...

**Comment by frankrichter** [comment]
Chrome@Windows funktioniert jetzt einwandfrei, Android kann ich morgen noch testen.

**Comment by frankrichter** [comment]
Auch bei Chrome@Android alles in Ordnung jetzt.
