### ISSUE TITLE
Gültigkeit Cookie vz_authtoken

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#12]
In einer neuen Browsersitzung ist meistens ein erneutes Login erforderlich. Die Gültigkeit des Tokens in der volkszaehler.conf.php habe ich auf 1 Woche gesetzt.
In den Chrome-Entwicklertools steht für das Cookie vz_authtoken expires: session, obwohl 
[middleware.js#L92](https://github.com/andig/volkszaehler.org/blob/next/htdocs/frontend/javascripts/middleware.js#L92) das auf 2038 setzen will.

**Comment by andig** [comment]
Interessant. Mein Chrome zeigt 2038 an- kann es sein dass Du da irgendein Cookiekiller Plugin installiert hast?

**Comment by frankrichter** [comment]
Keine Plugins, vz_entities steht daneben bei mir ebenfalls mit 2038.
Am 26.01.2017 19:17 schrieb "andig" <notifications@github.com>:

**Comment by andig** [comment]
Finde den Fehler: https://github.com/andig/volkszaehler.org/blob/jwt/htdocs/frontend/javascripts/middleware.js#L93

der is mal geil. keine ahnung wieso das überhaupt irgendwas tut :O

**Comment by andig** [comment]
Merged...

**Comment by andig** [comment]
https://github.com/andig/volkszaehler.org/commit/d4e030d4735644472bc329248f4d8d0d6b202a4e

**Comment by frankrichter** [comment]
Da waren die JS-Engines unserer Browser wohl unterschiedlich tolerant...
Jetzt hab ich auch 2038, danke!
