### ISSUE TITLE
keine Middleware-Auswahl bei Erstellung von Kanälen

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#13]
Im next-Frontend kann man derzeit nur etwas mühsamer als sonst neue Kanäle erstellen. Bei middleware erscheint statt der aus master bekannten Dropdown-Box nur ein leeres Textfeld. Mit leerem Textfeld liefert das Formular beim abschicken einen Network Error, nach manueller Eingabe von ../middleware.php lässt sich der Kanal aber erstellen.

**Comment by andig** [comment]
Fixed and merged

**Comment by frankrichter** [comment]
Jepp, perfekt!
