### ISSUE TITLE
Firewall: Debug-Feature im Frontend

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#15]
Eine Installation mit aktiver Firewall akzeptiert keine Requests an die middleware, weil das authtoken nicht übergeben wird.
Für Debug-Zwecke, Export von raw-Zählerständen, Tests u.ä. folgende Idee: Da das Frontend die ganze Infrastruktur für Login und Token schon hat, wäre es doch sehr benutzerfreundlich, wenn man im Frontend ein Fensterchen öffnen könnte, wo man per üblichem Dropdown die passende Middleware wählen und darunter in ein einfaches Textfeld seinen Request (ab `?`) eingeben kann. Klick auf OK verpackt das ganze richtig (mit Token aus dem Cookie) und lädt die Antwort in neuem Tab/als File.

**Comment by andig** [comment]
Please move to vz/vz- this is interesting independently from jwt?

**Comment by frankrichter** [comment]
moved
