### ISSUE TITLE
Barcharts: Bereichsauswahl per Maus

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#16]
in den Barcharts verhält sich die Bereichswauswahl per Maus nicht korrekt: wählt man den Chart-Bereich bis ganz rechts aus, fehlt im geladenen Resultat trotzdem rechts eine Zeiteinheit; wählt man den Chart ab ganz links aus, erscheint im Resultat links eine zusätzliche (vorher nicht angezeigte) Zeiteinheit.

**Comment by frankrichter** [comment]
wahrscheinlich zu lösen mit #17

**Comment by andig** [comment]
Klappt das jetzt evtl auch?

**Comment by frankrichter** [comment]
Jo, das geht auch. Hatte ich eben nicht auf dem Schirm.
