### ISSUE TITLE
Barcharts: Anordnung der Balken

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#17]
Issues #6, #7 und #16 sind wahrscheinlich Konsequenzen aus der Anordnung der Balken um die linke Grenze des Intervalls, den sie repräsentieren. Dadurch müssen linke und rechte Grenze des Charts verschoben werden, was die o.g. issues verursacht.
Wenn es Komplexität einspart, wäre ich auf jeden Fall dafür, die Balken in die Intervallmitte zu schieben. 
Im Moment passen zwar die Achsenmarkierungen schön, aber ganz logisch ist es trotzdem nicht, wenn die Hälfte der Balken nicht in dem Intervall sind, in das sie gehören, sondern in dem davor. Besonders auffällig ist das, wenn man mit dem Cursor den Chart abfährt und auf die angezeigte Zeit achtet.

**Comment by andig** [comment]
Bitte nochmal nachtesten- ich habe die Timestamps jetzt wieder zurück geschubst.

**Comment by frankrichter** [comment]
Zu früh geschlossen...
Beim Diagrammtitel ist noch was faul: Ich wähle irgendwo im Januar "Monat", bekomme 31 Balken (1. - 31., also korrekt), über dem Diagramm steht aber 1. Januar - 2. Februar. Wahrscheinlich ein Relikt der verschobenen Timestamps. 
![screenshot 2017-02-05 22 25 34](https://cloud.githubusercontent.com/assets/13228024/22630021/1ef663ac-ebf2-11e6-9d05-04b2827da716.png)

**Comment by andig** [comment]
Egtl. ist das ein neues Issue ;) Tatsächlich brauche ich den Timestamp damit die letzte "gruppe" auch aus der DB kommt. Etwas doof, da muss ich den besten Weg zwischen API und FE suchen.

**Comment by frankrichter** [comment]
> Egtl. ist das ein neues Issue ;)

Es gibt aber definitiv einen Zusammenhang mit den verschobenen Timestamps, deswegen hab ich das hier untergebracht.
Ich habe meine Installation nochmal auf 850f088 zurückgespult und den gleichen Zeitbereich gewählt (siehe Screenshot). Hier ist der Diagrammtitel 1. Jan - 1. Feb., womit ich kein Problem hätte (so wird es ja im current mode auch gehandhabt, und wenn man sich noch 0:00 Uhr dazu denkt, ist es auch absolut korrekt). Für den 2. Feb. sehe ich allerdings keinen Grund, wenn der letzte Datensatz vom 31.01. ist.
![screenshot 2017-02-07 00 25 25](https://cloud.githubusercontent.com/assets/13228024/22671119/f1110c18-eccc-11e6-9a5c-4c011790e987.png)

**Comment by frankrichter** [comment]
Durch die Verschiebung gibt es auch ein paar Macken bei Zoom und Navigation im barchart mode.

Einige Testfälle:
- "month by day" liefert am 07.02. um 01:00 Uhr zwar 6 Balken für 01. - 06.02., stellt aber links davon noch 23h vom 31.01. dar (leer, ohne Balken)
- Klick auf "backward" liefert dann Balken für 31.12 - 30.01., also fehlt der 31.01. und die Monatgrenze wird überschritten
- Navigation im current mode in den Januar, dann Wahl von "month by day" ergibt Darstellung wie oben hochgeladener Screenshot vom 05.02. (alles ok bis auf Diagrammtitel); mehrfach backward springt um ganze Monate zurück (wie erwartet); 3 x backward ergibt Okt. 2016; forward schiebt nun allerdings um 1 Monat + 1 Tag: 01.10.-31.10. > 02.11.-01.12. > 03.12.-02.01. > 04.01.-03.02.
- durch Klick auf "now" kann man in allen consumption modes zusätzliche Balken links vom gewählten Zeitbereich erzeugen

**Comment by frankrichter** [comment]
Update:
Punkte 1, 2 und 4 treten nur bei aktivem Push-Server auf. Offenbar ist im consumption mode `vz.wui.tmaxnow = true` und `var delta = to - vz.options.plot.xaxis.max;` liefert dann ein negatives delta, deshalb die Erweiterung des Bereichs nach links (Punkt 1). 
Wenn `vz.options.plot.xaxis.max` in der Zukunft liegt, erklärt das auch die Headline.
Nur die Darstellung des Charts spricht dagegen, denn dort liegt xaxis.max ja trotz alldem in der Vergangenheit.

**Comment by frankrichter** [comment]
und hier die Lösung:

den Ärger erzeugt [plot.js#L352](https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/plot.js#L352), das habe ich aukommentiert

und dann [wui.js#L723](https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/wui.js#L723) so geändert:
`vz.options.plot.xaxis.max = vz.wui.adjustTimestamp(vz.options.plot.xaxis.max);`

Danach passt die Headline, Scrollen funktioniert vorwärts und rückwärts, und der Push-Server darf dabei auch laufen ohne was kaputt zu machen (es wird auch nicht mehr die aktuelle Leistung in die Tabelle gepusht wie zuvor, was mit der Einheit kWh ja Quark war).

**Comment by frankrichter** [comment]
Die bisherige Form von  [wui.js#L723](https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/wui.js#L723) hatte einen Vorteil:
dadurch wurde auch der aktuelle Tag/Monat/... in den Chart eingeschlossen, was ich absolut positiv finde.
Da es aber nur am rechten Rand Sinn macht und ansonsten den Scroll kaputt macht, hab ich noch eine Fallunterscheidung reingebaut:

```javascript
vz.options.plot.xaxis.max = (moment(vz.options.plot.xaxis.max).endOf(vz.options.mode).valueOf() > moment().valueOf())
				? moment(vz.wui.adjustTimestamp(vz.options.plot.xaxis.max)).add(1, vz.options.mode)
				: vz.wui.adjustTimestamp(vz.options.plot.xaxis.max);
```

Das läuft dann allerdings nur ohne Push-Server richtig schön. `vz.wui.zoomToPartialUpdate` wäre schnell so angepasst, dass es den Chart nicht verschiebt wenn `xaxis.max` sowieso in der Zukunft liegt ([wui.js#L510-512](https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/wui.js#L510)), aber es bleibt das Problem dass dann auch die barchart-channels push updates bekommen (Chart und Tabelle). Da weiß ich leider nicht wo ich ansetzen könnte.
Ein kombinierter Chart mit Bars für die Energiekanäle und Spannungswerten vom Push-Server funktioniert aber grundsätzlich, wenn man L510-512 mal rausnimmt.

Außerdem habe ich mit meinen Änderungen dafür gesorgt, dass Auto-Refresh auch consumption mode aktiv ist. Grundsätzlich ist das cool, da so der aktuelle Balken automatisch aktualisiert wird. Allerdings läuft das noch nicht sauber, denn im Moment hängt es bei jedem Refresh links noch einen Balken an. Weiterhin macht die Berechnung des Timeouts aus dem angezeigten Intervall dann keinen Sinn mehr.

**Comment by andig** [comment]
Lass uns das bitte erstmal in "normale" und "pushserver" Probleme trennen-
letztere kann ich momentan eh nicht nachtesten.

Fürs Erste hab ich den Überblick verloren :O

vg


2017-02-07 15:51 GMT+01:00 frankrichter <notifications@github.com>:

**Comment by frankrichter** [comment]
> Fürs Erste hab ich den Überblick verloren :O

sorry, ist ein bisschen wild geworden...

Ohne Rücksicht auf Push kannst du einfach die o.g. Änderungen einbauen:
[plot.js#L352](https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/plot.js#L352) raus
[wui.js#L723](https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/wui.js#L723) so ändern:

```javascript
vz.options.plot.xaxis.max = (moment(vz.options.plot.xaxis.max).endOf(vz.options.mode).valueOf() > moment().valueOf())
				? moment(vz.wui.adjustTimestamp(vz.options.plot.xaxis.max)).add(1, vz.options.mode)
				: vz.wui.adjustTimestamp(vz.options.plot.xaxis.max);
```

Teste das mal bei dir, wenn's dir auch gefällt schauen wir uns Auto-Refresh und ggf. irgendwann noch Push an.

Grüße
Frank

**Comment by frankrichter** [comment]
Um dir meine Änderungen einfacher verwertbar zu schicken, müsste ich jetzt einen PR machen, oder? Wie geht das, brauch ich dafür einen fork von deinem Repo oder geht das auch ohne?

**Comment by andig** [comment]
> plot.js#L352 raus

macht seit den neuen Timestamps keinen Sinn mehr, sehe ich ein

> wui.js#L723 so ändern:

muss ich erstmal durchschauen. Auf jeden Fall genug Futter, vielen Dank!

**Comment by andig** [comment]
Die plot#352 ist eigentlich dafür da zu verhindern dass die Überschrift den nächsten Tag noch anzeigt (also 1.2.-7.2. statt ..-8.2.). Damit auch 1.12.-31.12. Das ist aber inkonsistent zum sonstigen Verhalten wo wirklich die _Grenzen_ angezeigt werden.

Was meinst Du?

**Comment by frankrichter** [comment]
Ich kann mit der aktuellen Headline leben, wenn man sich jeweils 0:00 dazu ergänzt ist es ja korrekt.
Wenn wir da was ändern, würde ich das generell machen und nicht nur im consumption mode. Was machen wir sonst bei gemischten Charts? Für die usability ist es wohl auch nix, wenn der gleiche Zeitraum mit unterschiedlichen Headlines präsentiert wird.
Wenn wir konsistent definieren, dass 0:00:00:000 für die Headline noch zum Vortag gehört, wäre es vielleicht intuitiver wie jetzt. Das sollte aber nur gelten, wenn Tage ohne Uhrzeit ausgegeben werden, sonst steht da dann 0:00 bis 23:59, was ja auch nicht richtig und nicht schön ist.
Auf keinen Fall würde ich dafür die Chart-Grenzen anfassen, das gibt nur Ärger wenn man damit weiterrechnet (wie oben passiert). Sondern so wie du meintest rein kosmetisch für die Headline.

**Comment by Saftwerk** [comment]
Wie wär's mit Headline Endwert einfach aufgerundet anzeigen?

**Comment by frankrichter** [comment]
Was willst du aufrunden? Wir reden ja gerade darüber, dass eigentlich ein Tag zuviel angezeigt wird.

**Comment by Saftwerk** [comment]
ich habe halt gelesen "_sonst steht da dann 0:00 bis 23:59, was ja auch nicht richtig und nicht schön ist._"

Ganz andere Alternative: 
Anstelle das Interval anzugeben als "Start bis Stop"
könnte man doch auch schreiben; Von Start und Dauer also z.B. 1.Mai - 31 Tage

**Comment by frankrichter** [comment]
Ich hab testweise mal das hier eingebaut:

```javascript
	var to = $.plot.dateGenerator(
		(format == '%a %e. %b %Y')
			? vz.options.plot.xaxis.max - 1
			: vz.options.plot.xaxis.max,
		vz.options.plot.xaxis
	);

```

Also wird das Enddatum dann um 1 Tag reduziert, wenn nur Datum, aber keine Uhrzeit angezeigt wird, und zwar generell. Find ich nach kurzem Test ganz schick.

PS: `vz.wui.updateHeadline` gibt es sowohl in wui.js als auch in plot.js - ich hab ne ganze Zeit an der falschen rumgefrickelt und mich gewundert warum es keinerlei Auswirkungen hat...

**Comment by andig** [comment]
> Ich kann mit der aktuellen Headline leben, wenn man sich jeweils 0:00 dazu ergänzt ist es ja korrekt.
Wenn wir da was ändern, würde ich das generell machen und nicht nur im consumption mode. Was machen wir sonst bei gemischten Charts? Für die usability ist es wohl auch nix, wenn der gleiche Zeitraum mit unterschiedlichen Headlines präsentiert wird.

+1

> Wenn wir konsistent definieren, dass 0:00:00:000 für die Headline noch zum Vortag gehört, wäre es vielleicht intuitiver wie jetzt. Das sollte aber nur gelten, wenn Tage ohne Uhrzeit ausgegeben werden, sonst steht da dann 0:00 bis 23:59, was ja auch nicht richtig und nicht schön ist.

Gut Idee, übernehme ich. 

> Auf keinen Fall würde ich dafür die Chart-Grenzen anfassen, das gibt nur Ärger wenn man damit weiterrechnet (wie oben passiert). Sondern so wie du meintest rein kosmetisch für die Headline.

+1

> Ich hab testweise mal das hier eingebaut:

...nicht cool. Wer manuell mitten in Tage zoomt wird damit verarscht :/

> PS ...

Merge defect, behebe ich.

**Comment by frankrichter** [comment]
> ...nicht cool. Wer manuell mitten in Tage zoomt wird damit verarscht :/

Meinst du? Ich zieh doch nur 1ms ab, mitten am Tag also kein Effekt.

**Comment by andig** [comment]
Doh, stimmt. Alternativ hätte ich gecheckt ob wir exakt die Grenze haben. Deine Variante ist besser :)

Viele Grüße,
Andreas

**Comment by andig** [comment]
pushed https://github.com/andig/volkszaehler.org/commit/1593ec7bca2affc7d12851bbeeaa0d9cc9523203

**Comment by frankrichter** [comment]
Danke! Ich finde nur den Kommentar bzgl. consumption mode ein bisschen missverständlich, denn es gilt ja unabhängig von mode.
Wäre auch was für den master, oder?

**Comment by andig** [comment]
> Wäre auch was für den master, oder?

See https://github.com/volkszaehler/volkszaehler.org/pull/574

**Comment by frankrichter** [comment]
1593ec7 deckt nur die im Lauf des Threads aufgekommene Headline-Kosmetik ab.
Die aktuelle Version hat nach wie vor das oben beschriebene Problem bei "scroll forward".
Die diskutierten Änderungen in  https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/plot.js#L352 und https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/wui.js#L723 sollten auch noch rein.

**Comment by andig** [comment]
Kam mir gleich komisch vor. Versuchs bitte nochmal.

**Comment by frankrichter** [comment]
Zeile 725 braucht noch ein `vz.wui.adjustTimestamp` innerhalb von `moment()`, sonst passieren unerwünschte Sachen am rechten Rand (siehe Screenshot, gespeichert um 1:30 Uhr).
![screenshot 2017-02-13 01 31 11](https://cloud.githubusercontent.com/assets/13228024/22867662/5b1a9570-f18c-11e6-95db-3be18991e548.png)

Zeile 725 komplett:
`? moment(vz.wui.adjustTimestamp(vz.options.plot.xaxis.max)).add(1, vz.options.mode)`

Zusätzlich hab ich noch eine Änderung für Auto-Refresh, die sieht aber noch etwas wirr aus. Dazu schreib ich morgen was.

**Comment by andig** [comment]
Neuer Versuch. Langsam verzweifele ich.

**Comment by frankrichter** [comment]
Musst du nicht. Jetzt funktioniert es soweit, nur mode=hour lieferte nach der Aktualisierung einen JS-Error.
Dafür muss in Zeile 698 und 699 noch `period `durch `vz.options.mode` ersetzt werden, dann läuft es wieder.
Zeile 724 halte ich aktuell für verzichtbar, weil es mode=week gar nicht gibt (zumindest nicht per Dropdown im Frontend). Habe ich auch noch nie vermisst.

**Comment by andig** [comment]
Bitte nochmal testen.

**Comment by frankrichter** [comment]
Ja, jetzt geht auch hour wieder, danke.
Dann würde ich vorschlagen, wir machen dieses Issue jetzt mal zu, lang (und chaotisch) genug ist es ja...
Zum Auto-Refresh im consumption mode würde ich dann ein neues aufmachen, muss mir aber erst über das erwartete Verhalten klar werden.

**Comment by andig** [comment]
Thx
