### ISSUE TITLE
Barcharts: Zuordnung y-Achse

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#18]
Bei mir funktioniert die Zuordnung der Barchart-Kanäle zur y-Achse "kWh" nicht zuverlässig.

Ausgangslage: 2 Kanäle (Bezug, Lieferung) abonniert, Kanaltyp el. Energie (Zählerstände)
* wenn bei Reload des Frontends nur 1 Kanal aktiv war, wird bei Umschaltung von Current auf beliebigen Barchart-Mode rechts vom Chart eine y-Achse mit der Einheit kWh erzeugt und für die Darstellung verwendet (so soll es sein)
* wenn beide Kanäle aktiv waren, wird keine kWh-Achse erstellt, sondern die linke kW-Achse verwendet
* wenn man mit einem aktiven Kanal in den Barchart-Mode wechselt und danach den zweiten dazu wählt,
landet der erste auf der kWh-Achse, der zweite auf der kW-Achse, im allgemeinen natürlich mit unterschiedlicher Skalierung
* wenn man von einer korrekten Barchart-Darstellung (mit kWh-Achse) zurück zu Current wechselt, bleibt die kWh-Achse bestehen und wird für die dann geplottete Leistung benutzt statt der korrekten kW-Achse
* nach der ersten Zoom/Scroll/Auto-Refresh-Aktion im Current Mode gibt es grundsätzlich keine kWh-Achse mehr
* wenn ich im Barchart-Mode mit falscher Achsendarstellung einen weiteren Kanal abonniere, wird die kWh-Achse erstellt falls noch nicht vorhanden und alle angezeigten Kanäle dieser zugeordnet, auch wenn sie vorher fälschlicherweise der kW-Achse zugeordnet waren

**Comment by andig** [comment]
Kannst Du mal testen was passiert wenn Du in https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/wui.js#L738 nochmal folgende Zeile einbaust:

	vz.options.plot.axesAssigned = false; // force axis assignment

Welche Probleme bleiben dann noch übrig?

**Comment by frankrichter** [comment]
> Welche Probleme bleiben dann noch übrig?

Nur noch:
* wenn man mit einem aktiven Kanal in den Barchart-Mode wechselt und danach den zweiten dazu wählt,
landet der erste auf der kWh-Achse, der zweite auf der kW-Achse, im allgemeinen natürlich mit unterschiedlicher Skalierung

**Comment by andig** [comment]
Bitte nochmal testen, sollte jetzt tun.

**Comment by frankrichter** [comment]
Ja, tut!

**Comment by andig** [comment]
Na wird doch so langsam- danke für die vielen Tests!
