### ISSUE TITLE
consumption mode: "Yearly"

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#19]
Im consumption mode ist das grouping "Yearly" aktuell nicht funktionsfähig: JS-Error für `ts.daysInYear()`, das gibt es wohl so nicht ([wui.js#L681](https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/wui.js#L681)).

Ich hab jetzt das `switch case` ganz ausgebaut und mit moment.js allgemeingültig formuliert:
```javascript
/**
 * Timestamp rounding for group mode
 */
vz.wui.adjustTimestamp = function(ts, middle) {
	ts = moment(ts);

	if (middle)
		ts = moment((ts.startOf(vz.options.mode).valueOf() + ts.endOf(vz.options.mode).valueOf()) / 2);
	else
		ts.startOf(vz.options.mode);

	return ts.valueOf();
};
```
Test ist mit meiner Installation möglich.

**Comment by andig** [comment]
Es kann so einfach sein 😂
