### ISSUE TITLE
Skalierung y-Achse

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#23]
Ich habe eben eine etwas ungleichmäßige Skalierung der y-Achse beobachtet:
![screenshot_2017-07-04-13-49-49](https://user-images.githubusercontent.com/13228024/27830159-62237c44-60c5-11e7-98a2-b8df89b0fa5c.png)
Statt 0, 3, 5, 8, 10,... sollte da wahrscheinlich 0, 2.5, 5, 7.5, 10,... stehen.
Wenn das Maximum der Achse < 10 ist, wird eine Dezimale angezeigt, darüber nicht mehr.

**Comment by andig** [comment]
Igitt, da rundet wohl jemand grob fahrlässig. Passiert das nur bei next?

**Comment by frankrichter** [comment]
Ja, master zeigt W statt KW an, da passiert das bei üblichen Leistungen
nicht.

Am 04.07.2017 15:16 schrieb "andig" <notifications@github.com>:

**Comment by frankrichter** [comment]
`axis.tickDecimals` ist im oben gezeigten Fall 0, obwohl es 1 sein müsste. Ich vermute mal, dass das an `value *= axis.options.si.scaler;` (https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/plot.js#L200) liegt, denn vor der Multiplikation mit dem scaler hat value ja auch keine Dezimalen.

**Comment by andig** [comment]
Bitte prüfen- ggf. zwischendurch schon gelöst?

**Comment by frankrichter** [comment]
Mach ich, dauert aber ein bisschen - Urlaub :-)

Am 09.08.2017 09:53 schrieb "andig" <notifications@github.com>:

**Comment by frankrichter** [comment]
> Bitte prüfen- ggf. zwischendurch schon gelöst?

Problem besteht unverändert. Ich versteh an der fraglichen Stelle leider nicht genug, um selbst eine Lösung zu finden.
Vermutlich hängt es wie oben erwähnt mit `value *= axis.options.si.scaler;` zusammen, was es in master so nicht gibt (dort werden die Ticks in W, nicht in kW ausgegeben).

**Comment by andig** [comment]
Hi Frank,

hilfts wenn Du hier https://github.com/andig/volkszaehler.org/blob/next/htdocs/js/plot.js#L208 die -1 weg nimmst? Kann im Moment nur bedingt nachvollziehen was das alles soll...

Viele Grüße, Andreas

**Comment by frankrichter** [comment]
Hi Andreas,

das macht leider keinen Unterschied.
Meine Vermutung ist, dass axis.tickDecimals nichts von der Umrechnung mit
dem SI-Scaler mitbekommt.

Viele Grüße
Frank

2017-09-06 19:04 GMT+02:00 andig <notifications@github.com>:

**Comment by andig** [comment]
Hilft Dir das in der `plot.js`:

		vz.wui.tickFormatter = function (value, axis, tickIndex, ticks) {
			// last tick: return label instead
			if (ticks && tickIndex === ticks.length-1 && axis.options.axisLabel) {
				var si = axis.options.si || {};
				return '[' + si.prefix + si.unit + ']';
			}

			// first tick: calculate label formatting
			if (ticks && ticks.length && tickIndex === 0) {
				var maxValue = ticks[ticks.length-1];
				axis.options.si = vz.wui.scaleNumberAndUnit(maxValue, axis.options.axisLabel);

				// see vz.wui.formatNumber
				var si = axis.options.si;
				var precision = (Math.abs(si.number) < Math.pow(10, -(vz.options.precision + 1))) ? 0 :
					Math.max(0, vz.options.precision - Math.max(-1, Math.floor(Math.log(Math.abs(si.number))/Math.LN10)));

				axis.tickDecimals = precision;
			}

			// scale value according to unit
			value *= axis.options.si.scaler;

			return value.toFixed(axis.tickDecimals);
		};

Gefühlt habe ich jetzt immer eine Nachkommastelle zuviel, aber ich denke das ist der Preis für 1 Nachkommastelle bei zweistelligen Dezimalzahlen ;)

**Comment by frankrichter** [comment]
Damit hab ich auf jeden Fall keine unzulässige Rundung mehr. Ich beobachte
auch mehr Dezimalstellen als nötig, manchmal eine, manchmal auch zwei.

Damit kann man aber erstmal leben, danke!

2017-09-07 14:48 GMT+02:00 andig <notifications@github.com>:

**Comment by andig** [comment]
Die Anzahl der Stellen hängt von der größten Zahl (Axenmaximum) ab damit alle gleichartig formatiert werden. Ich checks ein...
