### ISSUE TITLE
Berechneter Verbrauchswert virtueller Kanäle zu gering

### ISSUE THREAD

**Issue by Christophhericks** [andig/volkszaehler.org#26]
Hallo,

ich nutze diese Version vom Volkszähler. Was mir aufgefallen ist, dass bei den errechneten Werten wie der Direktverbrauch oder die Gesamterzeugung aller Anlagen die Werte unter "Current" richtig angezeigt werden, aber wenn in die Säulenansicht gewechselt wird passt die Größe der Säulen nicht.

Ist das Problem bekannt? Danke.

**Comment by andig** [comment]
Hast Du ein Beispiel? Screenshot?

**Comment by Christophhericks** [comment]
Ja.

https://www.photovoltaikforum.com/volkszaehler-org-f131/saeulengrafik-mit-errechneten-werten-t127241.html#p1689485

In dem Forum habe ich einen Beitrag von dem Problem mit Bild dargestellt.

**Comment by andig** [comment]
Ich hab sowas ähnliches auch bemerkt- falsche Durchschnittswerte in der Tabelle unten, viel zu klein. Hab aber noch nicht nach Ursache gesucht. Hast Du rigendwelche Auflösungen auf den Kanälen? Wie oft bekommst Du da Messwerte, also wie „dicht“ sind die?

**Comment by frankrichter** [comment]
Auch bei den Leistungswert-Kanälen "kaufen" und "verkaufen" sind Durchschnitt und Verbrauch nicht plausibel, es wird wohl nicht nur bei den virtuellen Kanälen falsch gerechnet.

Bitte noch einen Screenshot vom gleichen Zeitraum im Current-Mode hochladen.

**Comment by Christophhericks** [comment]
Ja sobald mein VZ wieder läuft werde ich auch ein Screenshot von dem Current nachliefern. Aber ich habe Probleme mit dem VZ seit dem ich von auf Raspbian Stretch geupdatet habe. 
Aus Erfahrung kann ich aber sagen, dass die Werte in der Current-Ansicht passten.

**Comment by frankrichter** [comment]
Ich kann das für den aktuellen Commit-Stand so nicht bestätigen: Die Säulen und die Durchschnittswerte sind ok.

Allerdings fehlt mir der erste Datensatz der Periode (bei den Säulen und beim Verbrauch). Neues Issue?

![screenshot 2](https://user-images.githubusercontent.com/13228024/48920374-d6bdc200-ee98-11e8-954f-5ac63d3325ac.png)
![screenshot 3](https://user-images.githubusercontent.com/13228024/48920381-df15fd00-ee98-11e8-9eb3-906bda6bee76.png)

**Comment by frankrichter** [comment]
Beobachtung gilt nur für Zählerstände, was anderes habe ich in dieser
Installation nicht zum Testen.

Am Fr., 23. Nov. 2018, 10:43 hat andig <notifications@github.com>
geschrieben:

**Comment by Christophhericks** [comment]
<img width="1429" alt="bildschirmfoto 2018-11-24 um 10 42 52" src="https://user-images.githubusercontent.com/13520429/48966647-f27ab280-efd5-11e8-9500-c26a8798247b.png">

Ich habe meine PHP ver. von 5 auf PHP 7 aktualisiert und jetzt bekomme ich auch für die Virtuellen Kanäle gescheit große Balken. Wobei es unten auf dem Säulenbild bei verkaufen und kaufen noch Problem beim Verbrauch gibt. Der Rest sollte passen.

<img width="1429" alt="bildschirmfoto 2018-11-24 um 10 49 08" src="https://user-images.githubusercontent.com/13520429/48966691-f9ee8b80-efd6-11e8-9f8f-2b546073c290.png">

Wo bei ich auf dem Bild am ersten Tag noch Schwierigkeiten habe.

> Hast Du rigendwelche Auflösungen auf den Kanälen? Wie oft bekommst Du da Messwerte, also wie „dicht“ sind die?

Nein ne Auflösung habe ich nur bei Zählern (2000/kwh). Bei den virtuellen Kanälen nicht.

**Comment by andig** [comment]
> Ich habe meine PHP ver. von 5 auf PHP 7 aktualisiert und jetzt bekomme ich auch für die Virtuellen Kanäle gescheit große Balken

Seltsam, aber php5 ist eh EOL.

> Wo bei ich auf dem Bild am ersten Tag noch Schwierigkeiten habe.

Mach bitte konkrete Fehlerbeschreibung und neues Issue- für Suchspiele fehlt mir einfach die Zeit :(
