### ISSUE TITLE
Virtual channel exponent function 'pow' missing

### ISSUE THREAD

**Issue by Feilner** [andig/volkszaehler.org#28]
Within:
`protected function createStaticContextFunctions()`

The exponent function pow is should be added		
`$this->ctx->def('pow');`

**Comment by andig** [comment]
Do you want to do a PR?

**Comment by Feilner** [comment]
Hi,

If you wish I can do it. 

the following php math functions would also be good to be added. 

sqrt, exp, log, (log10, log1p)




Best regards,

Oliver

Am So, 10. Feb 2019, um 20:36, schrieb andig:

**Comment by Feilner** [comment]
Added in pull request https://github.com/andig/volkszaehler.org/pull/30
