### ISSUE TITLE
Wrong Scaling for meter type 'water' in case of consumption of more than 1000l/h

### ISSUE THREAD

**Issue by nuccleon** [andig/volkszaehler.org#31]
The unit of water consumption changes from l/h to m³/h in case of a consumption of more than 1000l/h.
The legend shows the correct value of ~1.03 m³/h, but the scale is still in l/h mode.

![vz](https://user-images.githubusercontent.com/24713434/52959865-a900f000-3397-11e9-9f55-b3a52a81b12e.png)

**Comment by andig** [comment]
I guess thats an issue of "standard" volkszaehler? Could you reopen at the original repo instead?
