### ISSUE TITLE
Probleme bei der Docker-Installation

### ISSUE THREAD

**Issue by emeins** [andig/volkszaehler.org#32]
Ich bekomme beim 2 Schritt in der beschrieben Docker-Installation den folgenden Fehler:

ash-4.3# docker run --link db mysql -u root -pR00t+ -h db -e "CREATE DATABASE volkszaehler;"

ERROR: mysqld failed while attempting to check config
command was: "mysqld -u root -pR00t+ -h db -e CREATE DATABASE volkszaehler; --verbose --help"

mysqld: Can not perform keyring migration : Invalid --keyring-migration-source option.
2019-03-07T19:12:13.509964Z 0 [ERROR] [MY-011084] [Server] Keyring migration failed.
2019-03-07T19:12:13.513006Z 0 [ERROR] [MY-010119] [Server] Aborting

**Comment by andig** [comment]
Google geschaut? Sagt mir nix, im Zweifel andere DB nehmen :/

**Comment by andig** [comment]
Ahh, warte! Da muss zweimal mysql nacheinander rein?!

**Comment by emeins** [comment]
Mit:
docker run --link db mysql **mysql** -u root -pR00t+ -h db -e "CREATE DATABASE volkszaehler;"
läuft es jetzt durch.

Zu der docker.conf.php - gibt es da ein Template oder muss die nur leer existierten?

**Comment by andig** [comment]
Die muss halt auf die richtige Datenbank zeigen ;)

**Comment by emeins** [comment]
Hast Du zur docker.conf.php noch ein Tip?
docker run --link db -v $(pwd)/etc/**_docker.conf.php_**:/vz/etc/volkszaehler.conf.php volkszaehler/volkszaehler /vz/bin/doctrine orm:schema-tool:create


Was soll da drin stehen?

**Comment by andig** [comment]
Das ist eine normale config, da gehört die db rein! War wohl nicht offensichtlich :/

**Comment by andig** [comment]
Ich hab die readme entsprchend aktualisiert.

**Comment by emeins** [comment]
Und schon läuft es. ;-) Danke.

**Comment by schlaubi666** [comment]
bis dahin fkt es.

sudo docker run --name db -e MYSQL_ROOT_PASSWORD=R00t+ mysql
sudo docker run --link db mysql mysql -u root -pR00t+ -h db -e "CREATE DATABASE volkszaehler;"

sudo docker logs db zeigt:

 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.16'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
[System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060

dann habe ich touch etc/docker.conf.php gemacht ( also eine leer Datei erzeugt ) und 
sudo docker run --link db -v $(pwd)/etc/docker.conf.php:/vz/etc/volkszaehler.conf.php volkszaehler/volkszaehler /vz/bin/doctrine orm:schema-tool:create

gemacht , dann bekomme ich folgende Fehler

In AbstractMySQLDriver.php line 93:

  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 31:

  SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

  SQLSTATE[HY000] [2002] Connection refused


orm:schema-tool:create [--dump-sql]
