### ISSUE TITLE
Max und Min bei bei der Aggregation möglich?

### ISSUE THREAD

**Issue by emeins** [andig/volkszaehler.org#34]
Was noch gut wäre, wenn bei der Datenaggregation noch die Werte (Spalten) für max- & min-Wert gespeichert werden. Gerade bei den Counterwerten ist eine Mittelwertbildung nur bedingt verwendbar.

**Comment by andig** [comment]
Im Prinzip ja, ist aber ein Riesenchange. Was meinst Du mit Mittelwerten? Bei Zählern werden keine gebildet!

**Comment by emeins** [comment]
Ups, sehe gerade, dass er bei den Countern die letzten Werte im Aggregationszeitraum anzieht, passt also. Sorry, hatte ich nicht gesehen.
Woher holt er sich den Consuption-Wert - berechnet aus dem Delta mit dem vorangegangenem Zeitraum? Könnte man Consuption vielleicht noch in die Tabelle ablegen?

**Comment by andig** [comment]
> Könnte man Consuption vielleicht noch in die Tabelle ablegen?

PRs willkommen. Aber welches Problem willst Du eigentlich lösen?
