### ISSUE TITLE
Update Docker Image rpi-volkszaehler auf Docker Hub (bereits 2 Jahre alt)

### ISSUE THREAD

**Issue by sir106** [andig/volkszaehler.org#35]
das letzte Update des Docker Containers für RASPBERRY PI liegt inzwischen 2 Jahre zurück (https://hub.docker.com/r/andig/rpi-volkszaehler) - könntest Du ein Update hochladen?

ich habe leider bei meinem Versuch raspbian auf Buster zu aktualisieren (für PHP 7.1) das Image geschrottet - es bootet nicht mehr; selbst ein nagelneues Stretch Image das auf Buster Quellen aktualisiert wird führt zu dem gleichen Problem.

Parallel ist durch die neue Abhängigkeit von PHP7.1 die Installationsanleitung auf Volkszaehler nicht mehr aktuell / funktionsfähig... 

...daher der Versuch mit dem Docker Image ;)

**Comment by andig** [comment]
Einfach aktuelles Image nehmen- volkszaehler/volkszaehler.

**Comment by sir106** [comment]
funktioniert leider nicht; scheint nicht für Raspberry PI (armhf) vorzuliegen...

standard_init_linux.go:207: exec user process caused "exec format error"

**Comment by andig** [comment]
Kommt auf die Todo-Liste. Wunsch wäre ein multi-arch Docker image was leider nicht trivial ist :O

**Comment by sir106** [comment]
super! das ist klasse...  DANKE! wäre es sehr aufwändig das "andig/rpi-volkszaehler" Image bis dahin zu aktualisieren? 

Ich spendiere auch eine ausführliche step-by-step Installationsanleitung (entsteht gerade)

**Comment by andig** [comment]
Nein, das hatte zuviele Workarounds. Die Quellen gibts weiter unter vz/docker....
