### ISSUE TITLE
group=month liefert unvollständige Werte

### ISSUE THREAD

**Issue by grseidel** [andig/volkszaehler.org#36]
Hallo,

ich habe auf next aktualisiert, um über gravo Verbrauchswerte per grafana visualisieren zu können. Tageswerte funktionieren ok. Allerdings werden die Monatswerte fehlerhaft zurückgemeldet.

![Unbenannt](https://user-images.githubusercontent.com/47289599/55217304-7ef4e600-51ff-11e9-8228-aec1a71a1bb1.jpg)

Bei der Abfrage der middleware direkt durch
`wget "http://localhost/middleware.php/data/a39b2040-2217-11e9-bebb-adac00d601e3.json?from=1522215522000&to=1553755122000&tuples=640&group=month&options=consumption"
`
wird ebenfalls nur 1 Wert zurückgemeldet, obwohl in der Datenbank Werte für 2 Monate vorliegen.
`{"version":"0.4","data":{"tuples":[[1553755121575,114338.761,8519]],"uuid":"a39b2040-2217-11e9-bebb-adac00d601e3","from":1550816812164,"to":1553755121575,"mi
n":[1553755121575,114338.76092749],"max":[1553755121575,114338.76092749],"average":46661480.177,"consumption":93322960.354,"rows":2}}
`

Auch das Löschen der aggregate Tabelle schaffte keine Abhilfe....

**Comment by andig** [comment]
Gleicher Fehler wie https://github.com/volkszaehler/volkszaehler.org/pull/752? Diskission bitte im Hauptrepo weiter führen- das Fenster ist jetzt gemerged.
