### ISSUE TITLE
push server is not enabled in docker image

### ISSUE THREAD

**Issue by bgewehr** [andig/volkszaehler.org#37]
Could you please explain the best way how to persistently enable push server on the docker image?

Please help a docker newbie...

**Comment by andig** [comment]
Aktuell braucht es dafür einen zweiten Docker Container in dem der Service läuft da Container per Default "single-service" sind. In dem Container muss dann der Entrypoint überschrieben werden. Kannst Du die Frage bitte ins VZ repo transferieren? Ich überlege eine Lösung.
