### ISSUE TITLE
Current: Charts mit Lücken

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#8]
2 Darstellungsfehler, die es im master nicht gibt:
- Charts enden kurz vor dem rechten Rand, auch wenn es Datensätze für den Zeitbereich dahinter gibt.
- Wenn im gewählten Intervall kein Datensatz vorhanden ist, wird der Chart gar nicht gezeichnet (fällt auf bei meinen SBFspot Kanälen, die nur tagsüber Daten bekommen).

**Comment by andig** [comment]
Klingt nach Fehler in der MW. Kannst Du mal bitte next vs master jeweils 1 Kanal mit gleichen Timestamps darstellen und jeweil die MW Antwort auf den JSON Request posten?

**Comment by frankrichter** [comment]
Mach ich, dauert aber ein bisschen.
Am 18.01.2017 12:53 schrieb "andig" <notifications@github.com>:

**Comment by frankrichter** [comment]
Auch die Lücken sind weg wenn ich auf lines umstelle, dann wohl doch eher
Frontend statt Middleware, oder?
Am 18.01.2017 12:53 schrieb "andig" <notifications@github.com>:

**Comment by frankrichter** [comment]
Lässt sich beheben durch rausnehmen von [plot.js#L253](https://github.com/andig/volkszaehler.org/blob/next/htdocs/frontend/javascripts/plot.js#L253).

**Comment by andig** [comment]
D.h. beide Darstellungsfehler treten nur auf wenn der Darstellungsmodus "steps" ist, richtig?

**Comment by frankrichter** [comment]
Ja, nur bei "steps". Daten am rechten Rand erfinden ist nicht nötig, nur nicht löschen.

`tuples.pop();	// remove last, duplicate tuple` [jetzt L255](https://github.com/andig/volkszaehler.org/blob/next/htdocs/frontend/javascripts/plot.js#L255)

ist wohl kontraproduktiv, weil das den rechten Datenpunkt löscht, der uns jetzt fehlt. Um 'steps' darzustellen braucht man ja gerade einen Punkt mehr als man Datenpunkte hat (für 2 Punkte: Anfang, Ende und die "Ecke" dazwischen).

**Comment by andig** [comment]
Check, gute Analyse, baue ich ein!

Viele Grüße,
Andreas

**Comment by andig** [comment]
Fixed via https://github.com/andig/volkszaehler.org/commit/75412a8154c495b617bc11260b9ef037bf79cac5, will merge in `next` asap.
