### ISSUE TITLE
Current: Kanal-Selektion zerstört Chart

### ISSUE THREAD

**Issue by frankrichter** [andig/volkszaehler.org#9]
Wenn ich in der Tabelle einen Kanal mehrfach anklicke (toggle zwischen highlighted/non-highlighted) geht der Chart kaputt (vorhandener Chart rutscht immer weiter nach links und wird rechts durch konstante Linie ergänzt, auch die Waveform verändert sich u.U. - ein Reload beendet den Spuk).

**Comment by andig** [comment]
Passiert nur bei States, oder?  

Viele Grüße,
Andreas

**Comment by frankrichter** [comment]
States? Sorry, da steh ich grad auf dem Schlauch...

Grüße
Frank
Am 18.01.2017 11:41 schrieb "andig" <notifications@github.com>:

**Comment by andig** [comment]
Darstellungsart in der Kanaldefinition: Lines/ Steps/ States?

**Comment by frankrichter** [comment]
Ok. states habe ich nicht im Einsatz, sind alles Zählerstände in
steps-Darstellung.
Aber du bist auf der richtigen Spur, denn Änderung auf lines umgeht die
Problematik offenbar.
Am 18.01.2017 12:51 schrieb "andig" <notifications@github.com>:

**Comment by andig** [comment]
Also schuld ist diese Zeile https://github.com/andig/volkszaehler.org/blob/next/htdocs/frontend/javascripts/plot.js#L251 allerdings verstehe ich einfach nicht wieso. Der Loop läuft auf einer Kopie der Daten. Wenn ich entity.data.tuples als auch tuples logge sehe ich dass sich Beides (!!!!!) verändert und ich verstehe einfach nicht wieso. Bin ratlos...

**Comment by frankrichter** [comment]
Ohne zu verstehen was ich mir da anschaue:
Was ist mit [plot.js#L253](https://github.com/andig/volkszaehler.org/blob/next/htdocs/frontend/javascripts/plot.js#L253)?
Die gibt es in master - wui.js nicht.

**Comment by frankrichter** [comment]
Ich habe [L253](https://github.com/andig/volkszaehler.org/blob/next/htdocs/frontend/javascripts/plot.js#L253) einfach mal auskommentiert, das hilft zwar hier nix, behebt aber issue #8 (Lücken) und berichtigt die Steps-Darstellung (in next endete der Steps-Graph vorher mit einer Ecke statt mit waagrechter Linie).

**Comment by andig** [comment]
Will be fixed via https://github.com/andig/volkszaehler.org/commit/d769e3ab8e0ba828eb369c6c590ae4a40bcc4153

**Comment by frankrichter** [comment]
Änderung aus d769e3a getest, läuft! Danke!

**Comment by andig** [comment]
Habs gerade gepusht.
